/* ======================================================================= */
/* SAKSHAM APPLICATION CONSTANTS                                           */
/* ======================================================================= */

    const I18N_DICTIONARY = {
      en: {
        brand_name: "Saksham",
        portal_patient: "Patient Portal",
        tagline: "सक्षम • Empowering Cognitive Wellness, Routine Precision & Assisted Recall",
        emergency_sos: "Emergency SOS",
        read_screen: "Read",
        breathe: "Breathe",
        calendar_date: "Selected Date",
        timeframe_daily: "Daily",
        timeframe_weekly: "Weekly",
        timeframe_monthly: "Monthly Calendar",
        nav_routine: "1. Daily Routine & Cues",
        nav_games: "2. Mind Clinic Games",
        nav_vault: "3. Loved Ones & Face Recall",
        nav_movement: "4. Movement & Speech",
        nav_nutrition: "5. Nutrition & Hydration",
        nav_calendar_hub: "6. Calendar & Milestones",
        banner_badge: "Daily Routine & Cognitive Coordination",
        mini_cues_tab: "1. Memory Cues for Every Task (3 Chances + Hint)",
        mini_direct_tab: "2. Direct Schedule Checklist",
        evening_guard: "Evening Guard",
        audio_cue_bar: "Audio Cue Bar",
        wellness_guide: "Cognitive Wellness & Dietary Guide",
        badge_early_bird: "Early Bird",
        badge_mind_master: "Mind Master",
        badge_consistency: "Consistency Champ",
        badge_hydration: "Hydration Hero"
      },
      hi: {
        brand_name: "सक्षम (Saksham)",
        portal_patient: "मरीज़ पोर्टल (Patient Portal)",
        tagline: "सक्षम • संज्ञानात्मक स्वास्थ्य, दिनचर्या सटीकता और त्वरित स्मरण",
        emergency_sos: "आपातकालीन SOS",
        read_screen: "स्क्रीन पढ़ें",
        breathe: "गहरी सांस लें",
        calendar_date: "चुनी गई तारीख",
        timeframe_daily: "दैनिक कार्य",
        timeframe_weekly: "साप्ताहिक प्रगति",
        timeframe_monthly: "मासिक कैलेंडर",
        nav_routine: "1. दैनिक दिनचर्या और संकेत",
        nav_games: "2. माइंड क्लिनिक गेम्स",
        nav_vault: "3. प्रियजन और चेहरे की पहचान",
        nav_movement: "4. शारीरिक गति और वाणी",
        nav_nutrition: "5. पोषण और जलयोजन",
        nav_calendar_hub: "6. कैलेंडर और उपलब्धियां",
        banner_badge: "दैनिक दिनचर्या और संज्ञानात्मक समन्वय",
        mini_cues_tab: "1. स्मृति संकेत (3 मौके + संकेत)",
        mini_direct_tab: "2. सीधी कार्य अनुसूची",
        evening_guard: "ईवनिंग गार्ड",
        audio_cue_bar: "ध्वनि संकेत बार",
        wellness_guide: "संज्ञानात्मक कल्याण और आहार गाइड",
        badge_early_bird: "प्रभात पंछी (Early Bird)",
        badge_mind_master: "माइंड मास्टर (Mind Master)",
        badge_consistency: "नियमितता चैंपियन (Consistency Champ)",
        badge_hydration: "जलदूत (Hydration Hero)"
      },
      mr: {
        brand_name: "सक्षम (Saksham)",
        portal_patient: "रुग्ण पोर्टल (Patient Portal)",
        tagline: "सक्षम • संज्ञानात्मक कल्याण, दैनंदिन सुसंवाद आणि AI सहाय्यक",
        emergency_sos: "आपत्कालीन SOS",
        read_screen: "स्क्रीन वाचा",
        breathe: "दीर्घ श्वास घ्या",
        calendar_date: "निवडलेली तारीख",
        timeframe_daily: "दैनिक कार्ये",
        timeframe_weekly: "साप्ताहिक प्रगती",
        timeframe_monthly: "मासिक दिनदर्शिका",
        nav_routine: "1. दैनंदिन दिनचर्या आणि संकेत",
        nav_games: "2. माइंड क्लिनिक खेळ",
        nav_vault: "3. आप्तेष्ट आणि स्मरण",
        nav_movement: "4. हालचाल आणि उच्चार",
        nav_nutrition: "5. पोषण आणि पाणी",
        nav_calendar_hub: "6. दिनदर्शिका आणि प्रगती",
        banner_badge: "दैनंदिन दिनचर्या आणि समन्वय",
        mini_cues_tab: "1. स्मरण संकेत (३ संधी + मदत)",
        mini_direct_tab: "2. थेट वेळापत्रक सूची",
        evening_guard: "इव्हनिंग गार्ड",
        audio_cue_bar: "ध्वनी संकेत पट्टी",
        wellness_guide: "आरोग्य व आहार मार्गदर्शक",
        badge_early_bird: "पहाटेचा पक्षी (Early Bird)",
        badge_mind_master: "माइंड मास्टर (Mind Master)",
        badge_consistency: "सातत्य चॅम्पियन (Consistency Champ)",
        badge_hydration: "जल नायक (Hydration Hero)"
      },
      ta: {
        brand_name: "சக்ஷம் (Saksham)",
        portal_patient: "நோயாளி போர்டல் (Patient Portal)",
        tagline: "சக்ஷம் • அறிவாற்றல் நல்வாழ்வு, நிகழ்நேர ஒருங்கிணைப்பு & AI உதவியாளர்",
        emergency_sos: "அவசர SOS",
        read_screen: "படிக்க",
        breathe: "மூச்சு பயிற்சி",
        calendar_date: "தேர்ந்தெடுக்கப்பட்ட தேதி",
        timeframe_daily: "தினசரி பணிகள்",
        timeframe_weekly: "வாராந்திர முன்னேற்றம்",
        timeframe_monthly: "மாதாந்திர நாட்காட்டி",
        nav_routine: "1. தினசரி நடைமுறை",
        nav_games: "2. மூளை விளையாட்டுகள்",
        nav_vault: "3. அன்பானவர்கள்",
        nav_movement: "4. உடற்பயிற்சி & பேச்சு",
        nav_nutrition: "5. உணவு & தண்ணீர்",
        nav_calendar_hub: "6. நாட்காட்டி & மைல்கற்கள்",
        banner_badge: "தினசரி ஒருங்கிணைப்பு",
        mini_cues_tab: "1. நினைவக குறிப்புகள் (3 வாய்ப்புகள்)",
        mini_direct_tab: "2. நேரடி அட்டவணை",
        evening_guard: "மாலை காவலர்",
        audio_cue_bar: "ஒலி குறிப்பு பார்",
        wellness_guide: "உணவு & ஆரோக்கிய வழிகாட்டி",
        badge_early_bird: "அதிகாலை பறவை (Early Bird)",
        badge_mind_master: "மன மேதை (Mind Master)",
        badge_consistency: "நிலைத்தன்மை சாம்பியன்",
        badge_hydration: "நீரேற்ற வீரன் (Hydration Hero)"
      },
      te: {
        brand_name: "సక్షం (Saksham)",
        portal_patient: "రోగి పోర్టల్ (Patient Portal)",
        tagline: "సక్షం • అభిజ్ఞా శ్రేయస్సు, రోజువారీ సమన్వయం మరియు AI సహాయకుడు",
        emergency_sos: "అత్యవసర SOS",
        read_screen: "చదవండి",
        breathe: "శ్వాస తీసుకోండి",
        calendar_date: "ఎంచుకున్న తేదీ",
        timeframe_daily: "రోజువారీ పనులు",
        timeframe_weekly: "వారపు పురోగతి",
        timeframe_monthly: "నెలవారీ క్యాలెండర్",
        nav_routine: "1. రోజువారీ దినచర్య",
        nav_games: "2. మైండ్ క్లినిక్ ఆటలు",
        nav_vault: "3. ఆప్తులు & గుర్తింపు",
        nav_movement: "4. కదలిక & సంభాషణ",
        nav_nutrition: "5. పోషణ & నీరు",
        nav_calendar_hub: "6. క్యాలెండర్ & మైలురాళ్ళు",
        banner_badge: "రోజువారీ సమన్వయం",
        mini_cues_tab: "1. జ్ఞాపకశక్తి ఆధారాలు (3 అవకాశాలు)",
        mini_direct_tab: "2. ప్రత్యక్ష జాబితా",
        evening_guard: "సాయంత్రం రక్షణ",
        audio_cue_bar: "ఆడియో సూచికల పట్టీ",
        wellness_guide: "ఆరోగ్య & ఆహార మార్గదర్శి",
        badge_early_bird: "ఉదయపు మేల్కొలుపు (Early Bird)",
        badge_mind_master: "మైండ్ మాస్టర్ (Mind Master)",
        badge_consistency: "క్రమశిక్షణ ఛాంపియన్",
        badge_hydration: "హైడ్రేషన్ హీరో (Hydration Hero)"
      },
      bn: {
        brand_name: "সক্ষম (Saksham)",
        portal_patient: "রোগী পোর্টাল (Patient Portal)",
        tagline: "সক্ষম • জ্ঞানীয় সুস্থতা, দৈনন্দিন সমন্বয় ও বুদ্ধিমান সহায়ক",
        emergency_sos: "জরুরি এসওএস",
        read_screen: "স্ক্রিন পড়ুন",
        breathe: "শ্বাস নিন",
        calendar_date: "নির্বাচিত তারিখ",
        timeframe_daily: "দৈনিক কাজ",
        timeframe_weekly: "সাপ্তাহিক অগ্রগতি",
        timeframe_monthly: "মাসিক ক্যালেন্ডার",
        nav_routine: "1. দৈনন্দিন রুটিন ও সংকেত",
        nav_games: "2. মাইন্ড ক্লিনিক গেমস",
        nav_vault: "3. প্রিয়জন ও স্মৃতি",
        nav_movement: "4. অঙ্গ সঞ্চালন ও বাক্যালাপ",
        nav_nutrition: "5. পুষ্টি ও জলপান",
        nav_calendar_hub: "6. ক্যালেন্ডার ও মাইলফলক",
        banner_badge: "দৈনন্দিন রুটিন সমন্বয়",
        mini_cues_tab: "1. স্মৃতি সংকেত (৩টি সুযোগ + ইঙ্গিত)",
        mini_direct_tab: "2. সরাসরি তালিকা",
        evening_guard: "সন্ধ্যা গার্ড",
        audio_cue_bar: "অডিও কিউ বার",
        wellness_guide: "স্বাস্থ্য ও খাদ্য নির্দেশিকা",
        badge_early_bird: "ভোরের পাখি (Early Bird)",
        badge_mind_master: "মাইন্ড মাস্টার (Mind Master)",
        badge_consistency: "ধারাবাহিকতা চ্যাম্পিয়ন",
        badge_hydration: "হাইড্রেশন হিরো (Hydration Hero)"
      },
      gu: {
        brand_name: "સક્ષમ (Saksham)",
        portal_patient: "દર્દી પોર્ટલ (Patient Portal)",
        tagline: "સક્ષમ • માનસિક સુખાકારી, દૈનિક સંકલન અને AI સહાયક",
        emergency_sos: "કટોકટી SOS",
        read_screen: "વાંચો",
        breathe: "શ્વાસ લો",
        calendar_date: "પસંદ કરેલી તારીખ",
        timeframe_daily: "દૈનિક કાર્યો",
        timeframe_weekly: "સાપ્તાહિક પ્રગતિ",
        timeframe_monthly: "માસિક કેલેન્ડર",
        nav_routine: "1. દૈનિક દિનચર્યા",
        nav_games: "2. માઇન્ડ ક્લિનિક રમતો",
        nav_vault: "3. સ્વજનો અને ઓળખ",
        nav_movement: "4. હલનચલન અને વાણી",
        nav_nutrition: "5. પોષણ અને હાઇડ્રેશન",
        nav_calendar_hub: "6. કેલેન્ડર અને માઇલસ્ટોન",
        banner_badge: "દૈનિક દિનચર્યા સંકલન",
        mini_cues_tab: "1. મેમરી સંકેત (3 તક + સંકેત)",
        mini_direct_tab: "2. સીધી યાદી",
        evening_guard: "સાંજ રક્ષક",
        audio_cue_bar: "ઓડિયો સંકેત પટ્ટી",
        wellness_guide: "આરોગ્ય અને આહાર માર્ગદર્શિકા",
        badge_early_bird: "સવારનો પંખી (Early Bird)",
        badge_mind_master: "માઇન્ડ માસ્ટર (Mind Master)",
        badge_consistency: "સાતત્ય ચેમ્પિયન",
        badge_hydration: "જળ વીર (Hydration Hero)"
      },
      kn: {
        brand_name: "ಸಕ್ಷಮ (Saksham)",
        portal_patient: "ರೋಗಿ ಪೋರ್ಟಲ್ (Patient Portal)",
        tagline: "ಸಕ್ಷಮ • ಅರಿವಿನ ಸ್ವಾಸ್ಥ್ಯ, ನೈಜ ಸಮಯದ ಸಮನ್ವಯ ಮತ್ತು AI ಸಹಾಯಕ",
        emergency_sos: "ತುರ್ತು SOS",
        read_screen: "ಓದಿ",
        breathe: "ಉಸಿರಾಡಿ",
        calendar_date: "ಆಯ್ಕೆಮಾಡಿದ ದಿನಾಂಕ",
        timeframe_daily: "ದೈನಂದಿನ ಕಾರ್ಯಗಳು",
        timeframe_weekly: "ವಾರದ ಪ್ರಗತಿ",
        timeframe_monthly: "ಮಾಸಿಕ ಕ್ಯಾಲೆಂಡರ್",
        nav_routine: "1. ದೈನಂದಿನ ದಿನಚರಿ",
        nav_games: "2. ಮೈಂಡ್ ಕ್ಲಿನಿಕ್ ಆಟಗಳು",
        nav_vault: "3. ಆಪ್ತರು ಮತ್ತು ನೆನಪು",
        nav_movement: "4. ಚಲನೆ ಮತ್ತು ಮಾತು",
        nav_nutrition: "5. ಪೋಷಣೆ ಮತ್ತು ನೀರು",
        nav_calendar_hub: "6. ಕ್ಯಾಲೆಂಡರ್ ಮತ್ತು ಪ್ರಗತಿ",
        banner_badge: "ದೈನಂದಿನ ದಿನಚರಿ ಸಮನ್ವಯ",
        mini_cues_tab: "1. ನೆನಪಿನ ಸುಳಿವುಗಳು (3 ಅವಕಾಶಗಳು)",
        mini_direct_tab: "2. ನೇರ ವೇಳಾಪಟ್ಟಿ",
        evening_guard: "ಸಂಜೆ ರಕ್ಷಕ",
        audio_cue_bar: "ಆಡಿಯೋ ಸೂಚಕ ಪಟ್ಟಿ",
        wellness_guide: "ಆರೋಗ್ಯ & ಆಹಾರ ಮಾರ್ಗದರ್ಶಿ",
        badge_early_bird: "ಮುಂಜಾನೆಯ ಪಕ್ಷಿ (Early Bird)",
        badge_mind_master: "ಮೈಂಡ್ ಮಾಸ್ಟರ್ (Mind Master)",
        badge_consistency: "ಸ್ಥಿರತೆ ಚಾಂಪಿಯನ್",
        badge_hydration: "ಜಲ ವೀರ (Hydration Hero)"
      }
    };


    const DAILY_HOBBIES = [
      { title: "Pick One Flower from the Garden Bowl", desc: "Take a mixed bowl with colorful flowers or soft petals. Gently pick up one flower with your fingers, place it into a fresh cup of water, and enjoy its soothing scent." },
      { title: "Color Sorting with Soft Balls", desc: "Take 3 colorful soft balls from a bowl. Place all yellow ones on the left, and blue ones on the right with steady finger grasps." },
      { title: "Gentle Dice Roll & Counting Game", desc: "Roll a dice on the table. Count the dots out loud, then tap your finger on the desk that exact number of times." }
    ];


    const LEVEL_TIERS = [
      { level: 0, title: "Level 0: Cognitive Sprout", icon: "🌱", minXp: 0, maxXp: 100 },
      { level: 1, title: "Level 1: Mindful Seedling", icon: "🌿", minXp: 100, maxXp: 250 },
      { level: 2, title: "Level 2: Memory Blossom", icon: "🌸", minXp: 250, maxXp: 500 },
      { level: 3, title: "Level 3: Focus Warrior", icon: "⚡", minXp: 500, maxXp: 850 },
      { level: 4, title: "Level 4: Resilient Oak", icon: "🌳", minXp: 850, maxXp: 1300 },
      { level: 5, title: "Level 5: Neuro Champion", icon: "👑", minXp: 1300, maxXp: 2000 }
    ];


    const MULTILINGUAL_RESPONSES = {
      vault: {
        name: "Loved Ones Photo Vault (परिवार)",
        page: "vault",
        icon: "fa-images",
        theme: "from-amber-600 to-orange-600",
        spoken: {
          hi: "आपका परिवार फोटो वॉल्ट खोला जा रहा है। अपनों की तस्वीरें देखें।",
          mr: "तुमचा कुटुंब आणि आठवणींचा फोटो वॉल्ट उघडत आहे. आपुलकीच्या आठवणी पहा.",
          gu: "તમારો પરિવાર ફોટો વૉલ્ટ ખોલી રહ્યા છીએ. તમારા સ્વજનોની યાદો જુઓ.",
          kn: "ನಿಮ್ಮ ಕುಟುಂಬ ಫೋಟೋ ವಾಲ್ಟ್ ತೆರೆಯಲಾಗುತ್ತಿದೆ. ಪ್ರೀತಿಪಾತ್ರರ ಫೋಟೋಗಳನ್ನು ನೋಡಿ.",
          ml: "നിങ്ങളുടെ കുടുംബ ഫോട്ടോ വോൾട്ട് തുറക്കുന്നു. പ്രിയപ്പെട്ടവരുടെ ചിത്രങ്ങൾ കാണാം.",
          raj: "थांरो परिवार फोटो वॉल्ट खोल रया हां। घराळां री यादें देखो।",
          en: "Opening your Loved Ones Photo Vault and facial recall memory cards."
        },
        buttonText: {
          hi: "परिवार फोटो वॉल्ट खोलें",
          mr: "कुटुंब फोटो वॉल्ट उघडा",
          gu: "પરિવાર ફોટો વૉલ્ટ ખોલો",
          kn: "ಕುಟುಂಬ ಫೋಟೋ ವಾಲ್ಟ್ ತೆರೆಯಿರಿ",
          ml: "കുടുംബ ഫോട്ടോ വോൾട്ട് തുറക്കൂ",
          raj: "परिवार फोटो वॉल्ट खोलो",
          en: "Open Photo Vault Now"
        }
      },
      games: {
        name: "Mind Clinic Games & Tech Lab (खेल)",
        page: "games",
        icon: "fa-gamepad",
        theme: "from-[#387D82] to-[#1B4225]",
        spoken: {
          hi: "दिमागी कसरत और खेल शुरू किए जा रहे हैं। आनंद लें!",
          mr: "मन क्लिनिकचे मेंदूचे खेळ आणि सराव सुरू करत आहे. खेळाचा आनंद घ्या!",
          gu: "માઇન્ડ ક્લિનિક રમતો અને કસરત શરૂ થઈ રહી છે. મજા માણો!",
          kn: "ಮನಸ್ಸಿನ ಕ್ಲಿನಿಕ್ ಆಟಗಳನ್ನು ಮತ್ತು ಮೆದುಳಿನ ತರಬೇತಿಯನ್ನು ತೆರೆಯಲಾಗುತ್ತಿದೆ. ಆನಂದಿಸಿ!",
          ml: "മൈൻഡ് ക്ലിനിക്ക് കളികളും ഓർമ്മ വ്യായാമങ്ങളും തുറക്കുന്നു. ആസ്വദിക്കൂ!",
          raj: "थांरा दिमागी खेल और रमत सुरू कर रया हां। खेल को आनंद ल्यो!",
          en: "Opening Mind Clinic interactive games and cognitive drills for you now."
        },
        buttonText: {
          hi: "खेल और दिमागी कसरत शुरू करें",
          mr: "खेळ आणि मेंदूचा सराव सुरू करा",
          gu: "રમતો અને કસરત શરૂ કરો",
          kn: "ಆಟಗಳನ್ನು ಪ್ರಾರಂಭಿಸಿ",
          ml: "കളികൾ ആരംഭിക്കൂ",
          raj: "खेल और रमत सुरू करो",
          en: "Open Games Page Now"
        }
      },
      routine: {
        name: "Daily Routine & Medication (दिनचर्या व दवा)",
        page: "routine",
        icon: "fa-pills",
        theme: "from-teal-600 to-emerald-600",
        spoken: {
          hi: "आपकी दिनचर्या और दवाइयों का समय खोला जा रहा है।",
          mr: "तुमची दिनचर्या आणि औषधांचे वेळापत्रक उघडत आहे.",
          gu: "તમારી દિનચર્યા અને દવાઓનું સમયપત્રક ખોલી રહ્યા છીએ.",
          kn: "ನಿಮ್ಮ ದಿನಚರಿ ಮತ್ತು ಔಷಧಿಗಳ ವೇಳಾಪಟ್ಟಿಯನ್ನು ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
          ml: "നിങ്ങളുടെ ദിനചര്യയും മരുന്നുകളുടെ സമയക്രമവും തുറക്കുന്നു.",
          raj: "थांरी दिनचर्या और दवाई को टेम खोल रया हां।",
          en: "Opening your daily routine and medication timeline."
        },
        buttonText: {
          hi: "दिनचर्या और दवाइयां देखें",
          mr: "दिनचर्या आणि औषधे पहा",
          gu: "દિનચર્યા અને દવાઓ જુઓ",
          kn: "ದಿನಚರಿ ಮತ್ತು ಔಷಧಿಗಳನ್ನು ನೋಡಿ",
          ml: "ദിനചര്യയും മരുന്നുകളും കാണൂ",
          raj: "दिनचर्या और दवाई देखो",
          en: "Open Routine Page Now"
        }
      },
      movement: {
        name: "Movement & Speech Therapy (चलना व आवाज)",
        page: "movement",
        icon: "fa-person-walking",
        theme: "from-rose-600 to-red-600",
        spoken: {
          hi: "चलने और बोलने की थेरेपी, मेट्रोनोम और आवाज का अभ्यास खोला जा रहा है।",
          mr: "चालणे आणि आवाजाचा व्यायाम विभाग उघडत आहे.",
          gu: "ચાલવા અને બોલવાની કસરત વિભાગ ખોલી રહ્યા છીએ.",
          kn: "ನಡಿಗೆ ಮತ್ತು ಧ್ವನಿ ವ್ಯಾಯಾಮ ಪುಟವನ್ನು ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
          ml: "നടത്തവും ശബ്ദ വ്യായാമങ്ങളും തുറക്കുന്നു.",
          raj: "चालणो और बोलणो को व्यायाम खोल रया हां।",
          en: "Opening Movement and Speech therapy, including the Gait Metronome and LSVT Loud meter."
        },
        buttonText: {
          hi: "व्यायाम और थेरेपी खोलें",
          mr: "व्यायाम आणि थेरपी उघडा",
          gu: "કસરત અને થેરાપી ખોલો",
          kn: "ವ್ಯಾಯಾಮ ಮತ್ತು ಥೆರಪಿ ತೆರೆಯಿರಿ",
          ml: "വ്യായാമവും തെറാപ്പിയും തുറക്കൂ",
          raj: "व्यायाम और थेरेपी खोलो",
          en: "Open Movement & Speech Now"
        }
      },
      nutrition: {
        name: "Nutrition & Levodopa Guide (आहार व भोजन)",
        page: "nutrition",
        icon: "fa-apple-whole",
        theme: "from-emerald-600 to-teal-600",
        spoken: {
          hi: "भोजन और लेवोडोपा प्रोटीन टाइमिंग गाइड खोला जा रहा है।",
          mr: "आहार आणि पोषण मार्गदर्शक उघडत आहे.",
          gu: "આહાર અને પોષણ માર્ગદર્શિકા ખોલી રહ્યા છીએ.",
          kn: "ಆಹಾರ ಮತ್ತು ಪೋಷಣೆ ಮಾರ್ಗದರ್ಶಿ ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
          ml: "ഭക്ഷണക്രമവും പോഷകാഹാര വഴികാട്ടിയും തുറക്കുന്നു.",
          raj: "थांरो खान-पान और भोजन को तरीको खोल रया हां।",
          en: "Opening Nutrition and Levodopa protein timing guide."
        },
        buttonText: {
          hi: "खान-पान और पोषण गाइड खोलें",
          mr: "आहार आणि पोषण मार्गदर्शक उघडा",
          gu: "આહાર અને પોષણ માર્ગદર્શિકા ખોલો",
          kn: "ಆಹಾರ ಮಾರ್ಗದರ್ಶಿ ತೆರೆಯಿರಿ",
          ml: "ഭക്ഷണക്രമ ഗൈഡ് തുറക്കൂ",
          raj: "खान-पान तरीको खोलो",
          en: "Open Nutrition Guide Now"
        }
      },
      calendar: {
        name: "Monthly Adherence Calendar (कैलेंडर)",
        page: "calendar-hub",
        icon: "fa-calendar",
        theme: "from-sky-600 to-blue-600",
        spoken: {
          hi: "आपका मासिक कैलेंडर खोला जा रहा है।",
          mr: "कॅलेंडर विभाग उघडत आहे.",
          gu: "કૅલેન્ડર હબ ખોલી રહ્યા છીએ.",
          kn: "ಕ್ಯಾಲೆಂಡರ್ ಹಬ್ ತೆರೆಯಲಾಗುತ್ತಿದೆ.",
          ml: "കലണ്ടർ ഹബ് തുറക്കുന്നു.",
          raj: "थांरो कैलेंडर खोल रया हां।",
          en: "Opening your monthly adherence calendar."
        },
        buttonText: {
          hi: "मासिक कैलेंडर खोलें",
          mr: "कॅलेंडर उघडा",
          gu: "કૅલેન્ડર ખોલો",
          kn: "ಕ್ಯಾಲೆಂಡರ್ ತೆರೆಯಿರಿ",
          ml: "കലണ്ടർ തുറക്കൂ",
          raj: "कैलेंडर खोलो",
          en: "Open Calendar Hub Now"
        }
      },
      sos: {
        name: "Emergency SOS (आपातकालीन मदद)",
        page: "sos",
        icon: "fa-triangle-exclamation",
        theme: "from-rose-600 to-red-700",
        spoken: {
          hi: "आपातकालीन एसओएस तुरंत शुरू किया जा रहा है!",
          mr: "आपत्कालीन मदत लगेच सुरू करत आहे!",
          gu: "ઇમરજન્સી મદદ તરત જ શરૂ કરી રહ્યા છીએ!",
          kn: "ತುರ್ತು ಎಸ್‌ಒಎಸ್ ಅನ್ನು ತಕ್ಷಣ ಪ್ರಾರಂಭಿಸಲಾಗುತ್ತಿದೆ!",
          ml: "അടിയന്തിര സഹായം ഉടൻ ആരംഭിക്കുന്നു!",
          raj: "आपातकालीन मदद तुरंत सुरू कर रया हां!",
          en: "Activating Emergency SOS immediately!"
        },
        buttonText: {
          hi: "इमरजेंसी एसओएस",
          mr: "आपत्कालीन मदत",
          gu: "ઇમરજન્સી મદદ",
          kn: "ತುರ್ತು ಎಸ್‌ಒಎಸ್",
          ml: "അടിയന്തിര സഹായം",
          raj: "आपातकालीन मदद",
          en: "Emergency SOS"
        }
      },
      calm: {
        name: "Sensory Calm Reset (शांत श्वास)",
        page: "calm",
        icon: "fa-wind",
        theme: "from-teal-600 to-cyan-700",
        spoken: {
          hi: "शांत श्वास व्यायाम शुरू किया जा रहा है। धीरे-धीरे सांस लें।",
          mr: "शांत श्वास सराव सुरू करत आहे. हळूच श्वास घ्या.",
          gu: "શાંત શ્વાસોચ્છવાસ શરૂ થઈ રહ્યો છે. ધીમેથી શ્વાસ લો.",
          kn: "ಶಾಂತ ಉಸಿರಾಟವನ್ನು ಪ್ರಾರಂಭಿಸಲಾಗುತ್ತಿದೆ. ನಿಧಾನವಾಗಿ ಉಸಿರಾಡಿ.",
          ml: "ശാന്തമായ ശ്വസന വ്യായാമം ആരംഭിക്കുന്നു. പതുക്കെ ശ്വാസമെടുക്കൂ.",
          raj: "शांत श्वास को तरीको सुरू कर रया हां। धीमे सूं सांस ल्यो।",
          en: "Starting 4-7-8 sensory calm breathing reset. Take a slow, gentle breath."
        },
        buttonText: {
          hi: "शांत श्वास शुरू करें",
          mr: "शांत श्वास सुरू करा",
          gu: "શાંત શ્વાસ શરૂ કરો",
          kn: "ಶಾಂತ ಉಸಿರಾಟ",
          ml: "ശാന്തമായ ശ്വസനം",
          raj: "शांत श्वास",
          en: "Start Calm Reset"
        }
      }
    };

